- 
  exp_name: "DNAEdit_FLUX"
  dataset_yaml: edits.yaml
  model_type: "FLUX"
  sampler_type: "DNAEditFLUX"
  T_steps: 28
  T_start : 4
  n_avg: 1
  src_guidance_scale: 1
  tar_guidance_scale: 2.5
  mvg : 0.8
  seed: 0
 

