- 
  exp_name: "DNAEdit_SD3"
  dataset_yaml: edits.yaml
  model_type: "SD3"
  sampler_type: "DNAEditSD3"
  T_steps: 40
  T_start : 13
  src_guidance_scale: 1
  tar_guidance_scale: 3.5
  mvg : 0.8
  seed: 0
 

